# Generated by Django 4.1.3 on 2023-11-13 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counseling', '0002_alter_counseling_id_alter_counselingapplication_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='counselingapplication',
            name='test_date',
            field=models.DateField(default="2003-10-10"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='counselingapplication',
            name='test_timeslot',
            field=models.CharField(default="MON1", max_length=10),
            preserve_default=False,
        ),
    ]
