# Generated by Django 4.1.3 on 2023-11-09 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_counselors_students_user_birth_user_phone_number_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Counselors',
            new_name='Counselor',
        ),
        migrations.RenameModel(
            old_name='Students',
            new_name='Student',
        ),
    ]
