# Generated by Django 4.1.3 on 2023-11-12 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0005_alter_user_user_type"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[],
        ),
    ]
