# Generated by Django 4.1.3 on 2023-11-12 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0008_alter_student_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counselor',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
